version: '3.1'
services:
  nest-chat:
    image: postgres
    container_name: nest-chat
    restart: always
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./pg-data:/var/lib/postgresql/data
volumes:
  postgres: